FROM tiangolo/uwsgi-nginx-flask:python3.12
# 3.13 is not supported.
COPY --from=ghcr.io/astral-sh/uv /uv /uvx /bin/
ENV UV_PROJECT_ENVIRONMENT=/usr/local/
RUN touch README.md
COPY pyproject.toml uv.lock ./
COPY mwahahavote mwahahavote
RUN uv sync --no-default-groups --inexact --locked
COPY uwsgi.ini prestart.sh ./
COPY uwsgi.conf /etc/nginx/conf.d/
